In [1]:
from flood_prediction.interface.main import *
%load_ext autoreload
%autoreload 2

2023-09-08 11:18:53.050787: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-09-08 11:18:53.225209: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-09-08 11:18:53.225236: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-09-08 11:18:53.263166: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-09-08 11:18:54.334618: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-09-08 11:18:54.334757: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-09-08 11:18:54.334771: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.

In [4]:
from flood_prediction.ml_logic.data_prep import *

df = get_data_and_targets()

Getting Weather Data
<Response [200]>
Getting Flood Data

In [5]:
df

,date,T(degC),rain(mm),surf_press(hPa),wind_s(km/h),wind_dir(deg),soil_moist_0_to_7cm(m3),soil_moist_7_to_28cm(m3),radiation(W/m2),river_discharge(m3/s),target
0,1984-01-01 00:00:00,19.2,0.0,982.1,4.5,331.0,0.251,0.278,0.0,48.77,0
1,1984-01-01 01:00:00,19.1,0.0,981.9,4.5,331.0,0.251,0.278,0.0,48.77,0
2,1984-01-01 02:00:00,18.6,0.0,982.0,4.1,345.0,0.251,0.278,0.0,48.77,0
3,1984-01-01 03:00:00,18.2,0.0,981.9,3.6,6.0,0.251,0.278,0.0,48.77,0
4,1984-01-01 04:00:00,17.7,0.0,981.9,3.7,11.0,0.251,0.278,0.0,48.77,0
...,...,...,...,...,...,...,...,...,...,...,...
347728,2023-09-01 16:00:00,16.0,0.0,982.2,7.3,237.0,0.412,0.430,217.0,40.11,0
347729,2023-09-01 17:00:00,15.2,0.0,981.9,6.4,232.0,0.412,0.430,132.0,40.11,0
347730,2023-09-01 18:00:00,14.5,0.0,982.2,4.2,239.0,0.412,0.430,79.0,40.11,0
347731,2023-09-01 19:00:00,13.6,0.0,982.7,5.2,245.0,0.412,0.430,29.0,40.11,0
347732,2023-09-01 20:00:00,13.4,0.0,982.9,3.2,207.0,0.413,0.430,2.0,40.11,0

In [7]:
df.columns

Index(['date', 'T(degC)', 'rain(mm)', 'surf_press(hPa)', 'wind_s(km/h)',
       'wind_dir(deg)', 'soil_moist_0_to_7cm(m3)', 'soil_moist_7_to_28cm(m3)',
       'radiation(W/m2)', 'river_discharge(m3/s)', 'target'],
      dtype='object')

In [6]:
df.dtypes

date                        datetime64[ns]
T(degC)                            float64
rain(mm)                           float64
surf_press(hPa)                    float64
wind_s(km/h)                       float64
wind_dir(deg)                      float64
soil_moist_0_to_7cm(m3)            float64
soil_moist_7_to_28cm(m3)           float64
radiation(W/m2)                    float64
river_discharge(m3/s)              float64
target                               int64
dtype: object